### PR TITLE
Feat: Contacts Page/Report

### PR DESCRIPTION
**Pull request by Alriyashi**

### CODE REVIEW

**Review by shawnmuzick — CHANGES_REQUESTED** [review]
This file should not be in your commits:
image

This PR has merge conflicts on feedback.js, likely because it is out of date with the current state of Dev.

**Comment by Alriyashi** [comment]
I have removed the .DS_Store file. And I fix the merge conflicts

**Comment by shawnmuzick** [comment]
> I have removed the .DS_Store file. And I fix the merge conflicts

There are still conflicts:
image

At a glance, you can see these files aren't even close in a merge editor:
image

You should pull up to date copies of all of the branches, and from your feature branch, merge dev into it, and commit the result. Then, PR that resulting feature branch state into dev. There will be no conflicts, because the feature branch will be ahead of dev, while it is currently behind it. Whenever you merge into a parent branch, you should make sure the child branch is up to date with it's parent.

**Comment by Alriyashi** [comment]
Try now and let me know if the merge conflicts are not solved.

**Comment by shawnmuzick** [comment]
> Try now and let me know if the merge conflicts are not solved.

I think you chose your winners in the conflict incorrectly, or else intend something that I don't understand. Why does this revert dev's changes to that file?
image

I understand the additions of the validation bits, but this PR reverts a lot of code that was already in place on dev and doesn't have anything to do with the problem this PR is addressing. 
image

Why is ParseURL changed? How is that related? And why remove the documentation blocks?
image

My guess is that none of that is intentional, and was just merged improperly.

**Pull request closed without merging**
